[variables]
PORT = "8000"

[phases.setup]
nixPkgs = ['python3', 'gcc']
aptPkgs = ['build-essential']

[phases.install]
cmds = [
  'python3 -m ensurepip',
  'python3 -m pip install --upgrade pip',
  'pip install -r requirements.txt'
]

[start]
cmd = "gunicorn graph_project.wsgi:application --bind 0.0.0.0:$PORT"
