[phases.setup]
nixPkgs = ['python3', 'gcc', 'postgresql', 'libpq', 'pkg-config']

[phases.install]
cmds = ['pip install --upgrade pip setuptools wheel', 'pip install -r requirements.txt']

[start]
cmd = 'gunicorn graph_project.wsgi:application --bind 0.0.0.0:$PORT'
